# Generated by Django 4.2.4 on 2024-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
