# Generated by Django 4.2.4 on 2024-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='coordinates',
            field=models.CharField(default='0.0, 0.0', help_text='Latitude, Longitude (e.g., 40.7128, -74.0060)', max_length=50),
        ),
    ]
