# Generated by Django 4.2.4 on 2024-11-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='backend_device',
        ),
    ]
